# Permalinks
permalink:           pretty

# Setup
title:               Jaga Santagostino
tagline:             Web developer and open source lover.
url:                 http://jagasantagostino.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jaga Santagostino
  url:               https://twitter.com/jamigibbs
  email:             jami0821@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/kandros/kandros.github.io
#google_analytics:    UA-3363703-15
twitter:             kandros5591
github:              kandros

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
